name: qiskit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - numpy=1.22.4
  - matplotlib=3.5.3
  - networkx
  - graphviz          # system library
  - pygraphviz        # Python bindings
  - tqdm
  - pip:
      - qiskit==0.39.0
      - qiskit-aer==0.11.0
      - qiskit-ibm-runtime==0.8.0
      - qiskit-ibmq-provider==0.19.2
      - qiskit-terra==0.22
